### PR TITLE
Redesign HTTP interface

### PR DESCRIPTION
**Pull request by KovalevDima**

### CODE REVIEW

**Comment by Lipranu** [comment]
Another client interface option has been added: it separates query construction and client queries into different type classes. An example of what working with this interface would look like:
```haskell
main = do
  client <- initClient -- {client settings}
  runWriteTable client exampleTable [exampleDataSample]
  resp1 <- runReadTable client exampleTable exampleData
  mapM_ print resp1
  runRawExpression client "TRUNCATE exampleWriteRead"
  resp2 <- runReadView client exampleView exampleViewRecord $
    interpretTable @ExampleView (mkParameter 2) (mkParameter 6)
  mapM_ print resp2

exampleTable :: Proxy ExampleTable
exampleData :: Proxy ExampleData
exampleView :: Proxy ExampleView
exampleViewRecord :: Proxy ExampleViewRecord
```

**Comment by KovalevDima** [comment]
Underlying code code of your design implementation need to be refactored since it's too complicated.
IMO, getting rid of `Expression` ADT would make it much more easier to understand and maintain

I think we also need to move away from providing our own wrapper around http-client. It leads user to unnecessary difficulties during tuning of `http-client` `Manager`

I'm profiling different implementations right now. I'll post the results soon

**Comment by KovalevDima** [comment]
I've pushed profiling code for every version

**Comment by KovalevDima** [comment]
There are interesting difference between v2 and v3. Current implementation completely bad

<details>
  <summary> Current HTTP client design </summary>
  
```
	Sun Jun  9 13:37 2024 Time and Allocation Profiling Report  (Final)

	   profiler +RTS -A32m -AL256m -p -hy -L250 -l-agu -N -RTS

	total time  =        2.31 secs   (9237 ticks @ 1000 us, 4 processors)
	total alloc = 10,115,926,936 bytes  (excludes profiling overheads)

COST CENTRE                           MODULE                        SRC                                                    %time %alloc

throwSocketErrorIfMinus1RetryMayBlock Network.Socket.Internal       Network/Socket/Internal.hs:(208,1)-(209,53)             45.3    2.1
$fWritableIntoTableExampleData1       Profiler                      <no location info>                                      26.8   32.7
runResourceT                          Control.Monad.Trans.Resource  Control/Monad/Trans/Resource.hs:(190,1)-(197,18)        10.2    8.3
main                                  Profiler                      Profiler.hs:(43,1)-(68,23)                               7.2   48.4
connectResume                         Data.Conduit.Internal.Conduit src/Data/Conduit/Internal/Conduit.hs:(311,1)-(330,30)    3.2    2.6
toASCIIBytes                          Data.UUID.Types.Internal      src/Data/UUID/Types/Internal.hs:386:1-55                 1.6    1.7
sendAll                               Network.Socket.ByteString.IO  Network/Socket/ByteString/IO.hsc:(96,1)-(103,58)         1.1    0.7
```
image
</details>

<details>
  <summary> V2 HTTP client design </summary>

```
	Sun Jun  9 13:34 2024 Time and Allocation Profiling Report  (Final)

	   profiler-v2 +RTS -A32m -AL256m -p -hy -L250 -l-agu -N -RTS

	total time  =        0.67 secs   (2698 ticks @ 1000 us, 4 processors)
	total alloc = 3,678,404,944 bytes  (excludes profiling overheads)

COST CENTRE                           MODULE                      SRC                                              %time %alloc

$fWritableIntoTableExampleData1       ProfilerV2                  <no location info>                                88.3   89.4
toASCIIBytes                          Data.UUID.Types.Internal    src/Data/UUID/Types/Internal.hs:386:1-55           3.5    4.6
main                                  ProfilerV2                  ProfilerV2.hs:(46,1)-(68,23)                       3.3    0.7
requestBuilder                        Network.HTTP.Client.Request Network/HTTP/Client/Request.hs:(436,1)-(578,32)    2.4    5.3
throwSocketErrorIfMinus1RetryMayBlock Network.Socket.Internal     Network/Socket/Internal.hs:(208,1)-(209,53)        1.9    0.0
```
image
</details>


<details>
  <summary> V3 HTTP client design </summary>

```
	Sun Jun  9 13:36 2024 Time and Allocation Profiling Report  (Final)

	   profiler-v3 +RTS -A32m -AL256m -p -hy -L250 -l-agu -N -RTS

	total time  =        0.91 secs   (3631 ticks @ 1000 us, 4 processors)
	total alloc = 3,678,405,288 bytes  (excludes profiling overheads)

COST CENTRE                           MODULE                      SRC                                              %time %alloc

$fWritableIntoTableExampleData1       ProfilerV3                  <no location info>                                82.8   89.4
throwSocketErrorIfMinus1RetryMayBlock Network.Socket.Internal     Network/Socket/Internal.hs:(208,1)-(209,53)        9.8    0.0
toASCIIBytes                          Data.UUID.Types.Internal    src/Data/UUID/Types/Internal.hs:386:1-55           2.6    4.6
main                                  ProfilerV3                  ProfilerV3.hs:(47,1)-(68,23)                       1.7    1.3
writeExpression                       ClickHaskell.ClientV3       lib/ClickHaskell/ClientV3.hs:221:1-57              1.2    2.8
requestBuilder                        Network.HTTP.Client.Request Network/HTTP/Client/Request.hs:(436,1)-(578,32)    0.8    1.8
```
image
</details>

**Pull request merged**
