### PR TITLE
Fix hls support error in integration-testing

### PR DESCRIPTION
**Pull request by Lipranu**
In the integration-tests project, hls crashed with an error due to an incorrect project name in the hie.yaml file

### CODE REVIEW

**Comment by KovalevDima** [comment]
We could try to delete this file at all. HLS can generate the same config and use it automatically without file.
I've been having some problems without this file on experimentally built cabal and older than 2.8.0.0 HLS version. HLS of 2.8.x has many improvements to work with cabal monorepos, but most of them require cabal-install-3.12, which has not yet been released
Which versions of cabal and HLS do you use? @Lipranu

**Comment by Lipranu** [comment]
@KovalevDima, I do not have cabal and hls installed at the system level, I usually load them at the project level. In ClickHaskell env I got cabal-3.10.3.0 and hls-2.7.0.0 (ghc-9.6.5)

**Comment by KovalevDima** [comment]
Ok. I think we can just delete hie.yaml right now and forget about problems with project structure influence on HLS.
Would you do this in this PR?

**Comment by Lipranu** [comment]
After removing hie.yaml, hls works for me locally

**Review by KovalevDima — APPROVED** [review]

**Pull request merged**
